### ISSUE TITLE
Extension cannot be in 2 separate Auto state Rules

### ISSUE THREAD

**Issue by cannedenthusiasm** [AInoob/NooBoss#10]
If I have 2 Auto State Rules, with the same extension associated and "Only enable when matched" is used, then the extension will automatically disable if only one of the rules is matched. For example: 

Rule A & Rule B both have Extension C associated.
If Rule A & B are matched (using "Only enable when matched"), the extension is enabled and usable. 
If Rule A is matched, but Rule B is not, then extension will enable for a second, then disable (because Rule B is not matched). 

Thus, overriding Rule A.

**Comment by AInoob** [comment]
Hello there, the later the rule is, the higher priority it will be, hope this helps.
