### ISSUE TITLE
似乎被Chrome商店下架了

### ISSUE THREAD

**Issue by Yusei-StarDust** [AInoob/NooBoss#107]
如題，在extension的設定頁面顯示「這個擴充功能違反了 Chrome 線上應用程式商店政策。」，然後在商店中也搜尋不到顯示404_(:з」∠)_

**Comment by nopcall** [comment]
今天起床也发现了 能知道是什么原因么？

**Comment by XOKP** [comment]
具体违反了什么政策呢？🤔

**Comment by Mr54233** [comment]
怪不得我说我怎么少了一个扩展

**Comment by Itzamana** [comment]
谷歌商店净搞些幺蛾子…唉

**Comment by AzlanCoding** [comment]
https://developer.chrome.com/docs/webstore/troubleshooting/
是否有太多[permissions](https://developer.chrome.com/docs/webstore/troubleshooting/#excessive-permissions)
![image](https://user-images.githubusercontent.com/101229146/159192233-4d65ac90-2fb0-4732-a89d-a5421e44151f.png)

**Comment by AzlanCoding** [comment]
![image](https://user-images.githubusercontent.com/101229146/159449897-ffc02854-7fe4-4fb0-abc2-35f9ee0dfc25.png)
可以了！這個擴充功没有能違反了 Chrome 線上應用程式商店政策了。

**Comment by Yusei-StarDust** [comment]
嗯，也在商店中顯示出來了，那就close囉~
