### ISSUE TITLE
Export settings doesn't work

### ISSUE THREAD

**Issue by eugenesvk** [AInoob/NooBoss#12]
When I click **Export settings** nothing seems to happen, I don't get a prompt with an option to choose where to save them and couldn't find them manually (in case the addon just dumps the settings in a predefined location)
The **Import settings** works just fine
Vivaldi 1.11.882.4 (Official Build) (32-bit)
upd: sorry, was wrong about Chrome, it works just fine there, found the extracted options in the default download folder. Maybe a notification of a successful export would be nice

**Comment by AInoob** [comment]
Glad that it works! I will try to make some notification later.
