### ISSUE TITLE
Disabling Automatic Update of individual extensions.

### ISSUE THREAD

**Issue by mikhoul** [AInoob/NooBoss#13]
What would be really useful for security purpose is to have the possibility to disable/enable  the  Update of individual extensions.   It could be done by changing the path of update of selected extensions to localhost 0.0.0.0 and storing the original path somewhere so when the user enable it again it would just replace/rewrite the original path again for the update.

Being able to tell the user there is an update available for the extension even if auto-update is disabled would be wonderful.

I had this idea since last week 2 major account of extensions were hacked (Great Suspender + Social Fixer) and the hacker pushed a new update with malware inside. Since ChromeStore don't review addon by a human (like Mozilla do for Firefox in AMO) it would add a security layer where you could check yourself if the update is legit or not and decide to update it or not.

Regards :octocat:

**Comment by AInoob** [comment]
Thank you for the suggestion! I think this can be a very useful feature, I will try to implement it.

**Comment by AInoob** [comment]
Hello there, I think NooBoss does not have permission to change hostname, the only way I think NooBoss can do is to tell people how to edit the host file. On the other hand,downloading CRX file and install the extension would be a possible way, but the settings might be erased.

So I will put this idea into possible to-do list, and see what can I do with it.
