### ISSUE TITLE
不正常关闭浏览器经常会丢失规则

### ISSUE THREAD

**Issue by oldmenplus** [AInoob/NooBoss#14]
不正常关闭浏览器经常会丢失规则，重新配置好麻烦的诶，虽然有备份功能，但是还是好麻烦啊，没什么同步或者自动备份功能吗？

**Comment by AInoob** [comment]
感谢反馈。话说是在修改规则的时候吗？如果是的话，我后面会增加一个保存上一次关闭情况的功能，到时候就应该没问题了～

**Comment by AInoob** [comment]
Hello，最新版本会自动保存上次关闭时候的编辑，你可以测试一下～
