### ISSUE TITLE
列表视图名称过长显示问题

### ISSUE THREAD

**Issue by takboo** [AInoob/NooBoss#15]
当切换到列表视图时，如果名称过长，显示会出现问题，名称会与版本号出现重叠。
可以判断插件名称的长度，滚动展示。
或者将过长的部分用 ... 表示。
![image](https://user-images.githubusercontent.com/7644218/28256979-cfb72be6-6af9-11e7-8990-b68a6792426e.png)

**Comment by AInoob** [comment]
感谢提醒，会先隐藏多出的部分的～

**Comment by AInoob** [comment]
貌似已经解决了，如果没有，欢迎重新打开~
