### ISSUE TITLE
增加快速启动chrome app应用的功能

### ISSUE THREAD

**Issue by quericy** [AInoob/NooBoss#16]
目前没有快速途径在扩展中打开chrome app(例如Postman)。

只能通过扩展->插件主页->启动应用:
![](http://i.imgur.com/4J26uHB.png)
![](https://i.imgur.com/MAB8bIj.png)
希望能改进一下

**Comment by AInoob** [comment]
感谢反馈！这个会加入to-do的～
目前在重写二管家，所以要花不少时间～

**Comment by AInoob** [comment]
已经完成，哈哈
