### ISSUE TITLE
chrome插件隐藏相关

### ISSUE THREAD

**Issue by sli1989** [AInoob/NooBoss#17]
chrome在只保留一个图标位时，一般情况只显示ainoob。当进入匹配规则网站后，ainoob变为隐藏插件按钮（因为只保留一个图标位）。如果设置插件全部设置，则没有类似问题。能不能在设置部分插件隐藏情况下，始终保持ainoob插件显示。
谢谢。

**Comment by AInoob** [comment]
Hello，不是很清楚你的意思，可以弄个截图说明吗？

**Comment by sli1989** [comment]
@AInoob 
![1](https://user-images.githubusercontent.com/8521181/29237525-89ea4d4c-7f52-11e7-869d-2f50211bcfe0.png)
在一般情况下，设置了alnoob插件为显示。
![2](https://user-images.githubusercontent.com/8521181/29237536-a307a586-7f52-11e7-80b6-48948e036a6c.png)
进入设定了规则的网页后，alnoob插件变为了隐藏，有时候想进入设置还需要在点击右侧隐藏按钮。（可能chrome设置了只有三个显示位）
能不能强制设置alnoob插件显示。

**Comment by AInoob** [comment]
这个貌似不是拓展自己能控制的，你可以尝试把NooBoss拖到最左边，这样应该显示的优先级就高了～

话说我的可以显示好多个拓展（目前已经显示了13个），所以可能不同Chrome版本也不一样？

![deepinscreenshot_select-area_20170812133756](https://user-images.githubusercontent.com/7615460/29244041-7ba318e8-7f63-11e7-88d0-af1260cf40f4.png)

**Comment by sli1989** [comment]
是自己设置是否隐藏的。好吧，知道，谢啦。

**Comment by AInoob** [comment]
嗯呢～
