### ISSUE TITLE
Better History被频繁的关闭开启

### ISSUE THREAD

**Issue by JackHang** [AInoob/NooBoss#18]
没有设置Better History的自动管理，但是却频繁的关闭启动
![自动管理](https://user-images.githubusercontent.com/7665493/29441082-5d828c26-83fb-11e7-98c2-6acd59c54420.png)

![image](https://user-images.githubusercontent.com/7665493/29441093-706273d8-83fb-11e7-9538-20cf1f9cd3ff.png)

![image](https://user-images.githubusercontent.com/7665493/29441112-7f1ba458-83fb-11e7-9f52-09929a8f2053.png)

**Comment by AInoob** [comment]
Hello, 明天我会测试一下的～

**Comment by AInoob** [comment]
Hello, 你可以说一下在什么情况下会被频繁关闭开启吗？我这里貌似没有出现～

**Comment by JackHang** [comment]
好的，谢谢
