### ISSUE TITLE
Autostate rules don't work for github.com 

### ISSUE THREAD

**Issue by dsifford** [AInoob/NooBoss#19]
Hi there. Neat extension. Totally useful!

Just ran into an issue preventing me from enabling any autostate rules on github.com. I tried a few different ways to no avail. 

I confirmed that it's github.com causing the issue by setting the rule to some other domains and all others that I tried worked.

Let me know if there's anything I can help with. 

Thanks! 😄

**Comment by AInoob** [comment]
Hello there, can you please export your setting to me? Or can you make a screenshot or something? I want to reproduce the issue and find out what's going on and then fix the problem.

**Comment by dsifford** [comment]
@AInoob Sorry for the delay.. Thought the latest update might have fixed this and only just now got around to trying it..

Unfortunately, it still is not working (again, only on github.com).

Here's my config:

```json
{
    "autoState": true,
    "autoStateNotification": true,
    "autoStateRules": [
        {
            "action": "enableOnly",
            "ids": ["iajhmklhilkjgabejjemfbhmclgnmamf"],
            "match": { "isWildcard": false, "url": "https://trello.com" }
        },
        {
            "action": "enableOnly",
            "disabled": false,
            "ids": [
                "dgjhfomjieaadpoljlnidmbgkdffpack",
                "keefkhehidemnokodkdkejapdgfjmijf",
                "jlmafbaeoofdegohdhinkhilhclaklkp",
                "mmoahbbnojgkclgceahhakhnccimnplk",
                "ogcgkffhplmphkaahpmffcafajaocjbd"
            ],
            "match": { "isWildcard": false, "url": "https://github.com" }
        }
    ],
    "defaultPage": "autoState",
    "extensions": true,
    "groupList": [],
    "historyDisable": true,
    "historyEnable": true,
    "historyInstall": true,
    "historyRemove": true,
    "historyUpdate": true,
    "joinCommunity": false,
    "listView": true,
    "mainColor": { "a": 0.84, "b": 59, "g": 18, "r": 24 },
    "notificationDuration_autoState": "2",
    "notificationDuration_installation": -1,
    "notificationDuration_removal": "",
    "notificationDuration_stateChange": "2",
    "notifyInstallation": true,
    "notifyRemoval": false,
    "notifyStateChange": false,
    "recoExtensions": true,
    "sendUsage": true,
    "showAds": false,
    "sortOrder": "nameState",
    "subColor": { "a": 1, "b": 0, "g": 0, "r": 0 },
    "userscripts": true,
    "version": "0.1.5.5",
    "viewMode": "tile"
}
```

**Comment by dsifford** [comment]
![image](https://user-images.githubusercontent.com/5240018/29848532-455dc712-8cef-11e7-861d-26223ba4a473.png)

**Comment by AInoob** [comment]
Just see the comment, importing the options and trying it. Another person have also mentioned that NooBoss is slower than before, I think something is wrong, investigating. 

Thank you for letting me know!

**Comment by AInoob** [comment]
I tried out with your extensions and AutoState rules, and it looks fine. For slow, do you mean when first loading Github, it takes less 1 second to load, where before it might be like 0.1 seconds? If not, how much slow do you feel? Since another person also face the similar issue, I will still investigate into this. Thank you.

**Comment by AInoob** [comment]
Yep, I found a logic bug that can be improved, this would happen when you have more than one extension available for same website, in your case it's Github.com.  The update version would be 0.1.5.8, and it should fix the problem. Would really appreciate if you want to give me some feedback after the update.

**Comment by AInoob** [comment]
0.1.5.8 should fixed the bug, please tell me if this problem is fixed or not. Thank you for letting me know!

**Comment by dsifford** [comment]
Looks like it works! Thanks so much!

**Comment by AInoob** [comment]
Awesome! Thanks again for letting me know! :)
