### ISSUE TITLE
你好，关于今天更新的版本。

### ISSUE THREAD

**Issue by oenstep** [AInoob/NooBoss#21]
由于更新后发现没有原来版本好用（比如列表模式没了，加载速度慢了），能否给一下上一个版本的扩展文件（手动加载上一个版本扩展），一直都用着发现很不错，依赖很大了。邮箱oenstep@163.com

**Comment by oenstep** [comment]
由于是只是单纯的用户不太懂源码怎么编译，虽然能找到之前版本的源码（在commits中），请问是否是使用webpcak来编译成crx扩展文件。

**Comment by AInoob** [comment]
Hello，原来的版本地址： https://ainoob.com/api/file/nooboss/NooBoss_0.1.4.3.crx

编译的话，以前很蛋疼，现在0.1.5.x以后的只需要npm install 后 npm run build，就会生成在dist了。

列表模式会在之后增加，加载速度变慢了这个是什么情况，如果可以，可以上一个gif对比吗？感激不尽！

**Comment by oenstep** [comment]
谢谢作者回复，加载慢是出现在打开自动管理Tab的时候（这里会等待一下才出现对象的图片，旧版本也有一点不过旧版本的体验好一点），新版本一点开nooboos时候的加载速度确实是比原版本的快（试了几次），就我本身的体验为而言，问题不是很大，主要是列表模式我比较习惯，去除后非常的蛋疼，新版本推出了自定义颜色的确是很赞的，我觉得上一个版本的默认的皮肤已经很赞了（不过新版本感觉长宽不太适合。。我喜欢旧版本），新版本的拓展Tab下的管理，打开的时候拓展图片是单独一个一个的加载，旧版本的拓展图片有时候是一下子加载好，有时候好像是缩放一下（另一个模式转换为列表模式的效果），对了新版本的记忆上一次操作的Tab这个功能不错。

**Comment by oenstep** [comment]
![duibi](https://user-images.githubusercontent.com/12694723/29766147-64645c28-8c10-11e7-817d-9ebd9fff6274.gif)

**Comment by AInoob** [comment]
关于速度，的确发现了一个可以优化的地方，稍后更新。

UI的速度这个我可能要周末才能更新优化了，新的版本其实已经增加了很多功能，加上重写花了很多很多时间，哈哈，所以会在新的版本上优化优化再优化～

**Comment by AInoob** [comment]
1.5.8版本应该修复了自动管理的页面加载速度问题，已经上传了，到时麻烦测试一下是不是很流畅了，哈哈～

再次感谢～

**Comment by AInoob** [comment]
然后已经增加了列表模式，加上图标的加载速度也有了很大的提升，欢迎尝试～

**Comment by oenstep** [comment]
谢谢作者，我去试试。

**Comment by oenstep** [comment]
我试了一下，发现0.1.5.8版本的自动管理无法修改列表模式，以及重新打开nooboss时候会从关于Tab跳转到上次打开过的Tab。加载速度确实快乐，谢谢作者，等等发gif。

**Comment by oenstep** [comment]
![dui](https://user-images.githubusercontent.com/12694723/29961358-fe37d8ce-8f31-11e7-9fea-8f6a37841e61.gif)

**Comment by oenstep** [comment]
我好像没录拓展里面另外两个模式，加载的确是快了，0.1.5.8版本的自动管理无法修改列表模式，以及重新打开nooboss时候会从关于Tab跳转到上次打开过的Tab，不知是不是我一个人的问题，看看能不能解决。

**Comment by AInoob** [comment]
0.1.6.0版本全面支持各种模式了～

Tab的问题我回头再改，因为不是特别容易～

感谢建议，很有用！

**Comment by oenstep** [comment]
收到，谢谢作者，我去试试0.1.6.0版本。

**Comment by oenstep** [comment]
自动管理Tab是可以使用列表模式了，赞一个，可是整体的界面风格还是喜欢以前0.1.4.3。。。所以还是用着之前的版本，虽然说会有一些问题（用了那么久了好像没出过什么问题），不知道作者会不会改一下新版本的界面样式，长宽，字体大小什么的，还有新版本的自动管理中未选中的颜色不大好看太过黑了（旧版本合适我），好吧大概就这些，对了发现一个问题，自动管理tab中往下拉，发现偏黑色的颜色会覆盖顶部的Tab栏。

**Comment by oenstep** [comment]
自动管理tab中往下拉，发现偏黑色的颜色会覆盖顶部的Tab栏。


![fugai](https://user-images.githubusercontent.com/12694723/30033610-cc8a1c0c-91ce-11e7-83bc-f992234f7d4e.gif)

**Comment by AInoob** [comment]
覆盖的那里的确是个问题，你真的好细心啊！~\(≧▽≦)/~怒赞！

UI的话，现在已经开始工作了，没有太多时间弄NooBoss了，所以很难说什么时候会设计。不过Bug之类的一定会在第一时间修复的，尤其是像之前卡的那类bug～

大概10分钟后修复覆盖的问题，版本0.1.6.1。

**Comment by oenstep** [comment]
感谢作者，刚刚试了0.1.6.1，覆盖的问题解决了。问问作者，为什么不能沿用之前版本的UI呢？（之前版本感觉整体真的很不错，这是我的残念XD）对了作者我能问问这个userscript该怎么编译吗？https://github.com/YePpHa/maia-yt   能否大概讲讲怎么编译，一步一步讲解（有点尴尬，希望能在有空的情况下讲解）。再次感谢作者。

**Comment by AInoob** [comment]
超级详细的的确没有时间，确保你有terminal，然后有git，npm，webpack。这三个怎么安装，你就要自己找了～

下面是你需要打的命令：
git clone https://github.com/YePpHa/maia-yt.git

cd maia-yt

npm run install

mv webpack.userscript.prod.config.js webpack.config.js

webpack
然后就结束了，找一个dist的文件夹，里面应该就是你要的脚本了

**Comment by AInoob** [comment]
之前的UI的话，被人吐槽难看，然后我修改了一下，有的人说差不多，有的人说好看，有的说难看，我就放心了。。。只要不是全部说难看，我就心满意足了，于是改成了现在这个。
现在精力很少，基本是没法开发的节奏，修复bug什么的倒是不会结束，毕竟我也是二管家用户，哈哈～

**Comment by oenstep** [comment]
感谢作者回复，UI的话的确很难符合大家胃口XD,其实可以推出自定义用户按自己喜好改（这会不会有点难改代码！），我也想自己自定义的（自己设计UI什么的，不过无从下手），我下载了 cmder node.js了，cmder里面好像自带了git for windows  ， node.js 好像自带了 npm , 我去webpack官网看看如何安装。

**Comment by oenstep** [comment]
还有问一问，现在github大部分项目是不是都是采用webpack来编译的，是不是看到项目下游webpack.json就可以确认是采用webpack来编译。

**Comment by oenstep** [comment]
这个结果是不是安装webpack成功了！
![2017-09-07_132448](https://user-images.githubusercontent.com/12694723/30147464-0880cec8-93d1-11e7-916b-bfae0d964140.png)
![2017-09-07_132556](https://user-images.githubusercontent.com/12694723/30147465-08befbee-93d1-11e7-9084-abb73322d911.png)
![2017-09-07_132611](https://user-images.githubusercontent.com/12694723/30147466-08cca280-93d1-11e7-9850-f36e786c72ca.png)

**Comment by oenstep** [comment]
出了点问题
git clone https://github.com/YePpHa/maia-yt.git
cd maia-yt
npm run install 
到npm run install的时候cmder弹出了 missing script ：install  意思是缺少install插件？？是需要安装吗？类似webpack吗？？

![2017-09-07_133508](https://user-images.githubusercontent.com/12694723/30147629-00b01248-93d2-11e7-843a-d74e1c1186c5.png)

**Comment by oenstep** [comment]
C:\Users\Administrator\maia-yt\npm-debug.log
内容为

0 info it worked if it ends with ok
1 verbose cli [ 'F:\\software\\node\\node.exe',
1 verbose cli   'F:\\software\\node\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'install' ]
2 info using npm@3.10.10
3 info using node@v6.11.2
4 verbose stack Error: missing script: install
4 verbose stack     at run (F:\software\node\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at F:\software\node\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at F:\software\node\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (F:\software\node\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (F:\software\node\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (F:\software\node\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at F:\software\node\node_modules\npm\node_modules\read-package-json\read-json.js:311:12
4 verbose stack     at F:\software\node\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:456:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:443:12)
5 verbose cwd C:\Users\Administrator\maia-yt
6 error Windows_NT 6.1.7601
7 error argv "F:\\software\\node\\node.exe" "F:\\software\\node\\node_modules\\npm\\bin\\npm-cli.js" "run" "install"
8 error node v6.11.2
9 error npm  v3.10.10
10 error missing script: install
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

虽然可以发到npm的issue上，可是看了一下好像很多人提问的样子，所以试试贴到这里。
