### ISSUE TITLE
关于新版本二管家 默认皮肤颜色的问题

### ISSUE THREAD

**Issue by lki2019** [AInoob/NooBoss#23]
今天自动更新了，NooBoss_0.1.5.5

发现二管家默认的皮肤颜色是黑色，看惯了之前旧版的颜色

我修改下颜色吧，发现不能修改，
建议新版crx增加旧版皮肤颜色的切换功能

**Comment by lki2019** [comment]
我也发现新版有卡顿现象，果断换回了旧版crx

**Comment by lki2019** [comment]
github.com 今天浏览网站的时候 还有一些网站，感觉特别慢，我以为我网速的问题
把新版换成旧版crx 果断正常了，也不卡顿了····

**Comment by AInoob** [comment]
特别慢这个好严重啊！不是很确定是为什么。。。你可以试试最新版本吗？话说你的自动管理规则很多吗？

按理说二管家不拦截什么东西，不应该影响网速的，555

**Comment by lki2019** [comment]
群殴启用的扩展11个，还好吧 不算多吧

新版本第一皮肤颜色我适应不了，第2 浏览网页很卡，github.com 我浏览 回复卡的要S 

现在用的旧版 0.1.4.3
皮肤默认颜色 也适应，浏览网页也不卡，···

**Comment by AInoob** [comment]
哇，回复的好快！
新版皮肤可以自定义的，你试过吗？
卡这个我真的不是很确定为什么，一直没注意，我等下稍微测试一下，要是没发现什么，我就明天测试了～

感谢回复，很有用的信息！

**Comment by AInoob** [comment]
方面把你的自动管理规则导出给我吗？我想直接用你的测试一下～ 谢谢

**Comment by lki2019** [comment]
新版皮肤试过 点切换颜色 还是黑色

规则自动管理这个我不知道启用没 我反正是默认安装后什么都没动 一直这么用的，

我装的扩展也就是油猴啊  ABP IDM插件 之类的普通扩展··

**Comment by AInoob** [comment]
那有点奇怪，我平时开很多页面，没发现什么问题，我会继续调查的～

关于切换颜色切换不了的问题，如果你可以告诉我你的浏览器版本就好了，我这里Chrome和360急速都没有问题

**Comment by lki2019** [comment]
我是版本 55.0.2883.87 m

**Comment by AInoob** [comment]
Hello，颜色问题和卡的问题都解决了！ 版本0.1.5.9～

**Comment by lki2019** [comment]
好的，一会升级试试

**Comment by AInoob** [comment]
真的是神速回复，哈哈～
