### ISSUE TITLE
新版开启自动管理后导致页面频繁刷新

### ISSUE THREAD

**Issue by chingxuds** [AInoob/NooBoss#26]
如题，开启自动管理后，点击页面上的锚点（页内导航链接之类的），就会导致页面整体刷新，造成使用困扰

**Comment by AInoob** [comment]
你好，可以告诉我具体是什么网页吗？我这里测试Github随便点不会刷新啊，所以如果能提供网页，我就可以对症下药了～

**Comment by AInoob** [comment]
我天，我也遇到同样的问题了！！！这个我需要想想办法，感谢提醒！会在23小时内解决的。

**Comment by AInoob** [comment]
已经修复！ 版本0.1.5.9

再次感谢提醒！

**Comment by chingxuds** [comment]
感谢修复
