### ISSUE TITLE
希望能够添加自动启动规则针对每条规则的开关功能

### ISSUE THREAD

**Issue by chingxuds** [AInoob/NooBoss#27]
就是每条规则可以选择性打开或关闭，现在想临时关闭只能移除

**Comment by AInoob** [comment]
你好，这个已经在前几天支持了，自动管理在右边，有一个开启关闭的地方，你找一下？
上次看到你的建议就很快的增加了这个功能～

**Comment by chingxuds** [comment]
看到了，非常感谢，之前规则太长没主意到
