### ISSUE TITLE
繁体语言文件

### ISSUE THREAD

**Issue by zhtw2013** [AInoob/NooBoss#28]
繁体中文语言文件已制作完成，望能加入。
[Nooboss zh_TW.zip](https://github.com/AInoob/NooBoss/files/1280272/Nooboss.zh_TW.zip)

话说manifest_file:
  message: Manifest文件`

这个`号是不小心打的还是必要的？
我看简体语言文件有...我繁体也没删掉..如果是不必要的再麻烦作者删掉了

简体语言文件还有一句「 成功导出，文字名为"NooBoss.options"」
「文字名」应为「文件名」吧？

About.js
[About繁体用.zip](https://github.com/AInoob/NooBoss/files/1280310/About.zip)
这个我是直接把about文件里的简体部份弄成繁体而已
希望作者能自己提取繁体文本拿去改原来的About

二箱的繁体语言文件制作中...等等会传到二箱那里..

**Comment by AInoob** [comment]
超级感谢你的翻译！已经更新版本了，0.1.6.2。少年如果你在西雅图，让我请客啊～
