### ISSUE TITLE
[Feature request] Autostate "Enable/disable only if tab is active" and "Enable/disable only if tab is loaded"

### ISSUE THREAD

**Issue by malore** [AInoob/NooBoss#29]
I uses NooBoss because it helps to reduce the memory usage due to extensions, but this advantage is mitigated when there are a lot of tabs opened. I know this is my fault and I should work with as less as tabs possible but it would great if I could enable extensions only if they match a rule in the active tab, or in the loaded (non-frozen) ones.

**Comment by AInoob** [comment]
You are totally right, enable extension based on tab would be ideal, however, Chrome does not support this, so NooBoss is not able to to such thing.

**Comment by malore** [comment]
I'm sorry for going back to this issue but I noticed that RescueTime extension manages to track the active tab website. I don't know if that was the point.
