### ISSUE TITLE
Autostate feature isn't working as it supposed to do!!

### ISSUE THREAD

**Issue by Droyk** [AInoob/NooBoss#3]
Autostate isn't working like as describes in this video https://www.youtube.com/watch?v=fHkH25BmRCU
When user add the rule [only enable when or enable when] it disable on the given site and when the user add the rule [only disable when or disable when] it enable's on the given site 

**It's like it says's something else and does the opposite of it.**

& also autostate feature doesn't even disable or enable the extensions automatically on all the other sites except the given site.

Plz tell me what to do if you didn't understand my problem then I can give you a video example if you want too.

**Comment by Droyk** [comment]
[Okay I made a video](https://streamable.com/5s1h3) @AInoob plz see it and don't worry it just a 1 minute and 2-second video.

**Comment by AInoob** [comment]
Hello, I just saw this issue. Thank you for making a video! I it looks like there is a bug somewhere. I will try to reproduce the issue (I just tried once and it works fine on my laptop, so I will try again later today). If possible, are you willing to have a  Teamviewer with me? So I can see exactly what's wrong with NooBoss.

**Comment by AInoob** [comment]
One more thing, please check if your NooBoss version is 0.1.2.7 or not. Because last night I did fix a very lethal bug about Auto State. If it works after updating, please tell me so I can close this issue. Again, thank you for the feedback, it's very useful!

**Comment by Droyk** [comment]
>Teamviewer with me

Sorry won't be able to do that but I would totally be okay to provide any kind of help you need in fixing this issue. can't do any coding help though because I am not a developer.
> Please check if your NooBoss version is 0.1.2.7 or not

![image](https://cloud.githubusercontent.com/assets/15848350/23079401/ce030632-f572-11e6-8ca2-06686ee0c3a4.png)
as you can see it is 0.1.2.7 and didn't fix the issue at all

**Comment by AInoob** [comment]
Appreciate your support! Can you tell me the entire process? Like:
1.open browser
2.goto a.com
3.add enable only rule
4.and open a.com
5.nothing happened( extensions do not get enabled)
Please start with opening browser, so I can reproduce it. Thank you!
I will try to fix this tonight.

**Comment by AInoob** [comment]
Actually I just reproduced the bug, will fix it in 1 hour. Thank you again for telling me!

**Comment by AInoob** [comment]
Hello Droyk, so I just release the new update, which is version 0.1.2.8, and I think that should fix the problem. Another way to fix it is to go to Options, and cancel autoState first, then re-enable it, then it will request you tabs permission, and as soon as you allow it, you should be good to go!

**Comment by Droyk** [comment]
Hey just got back so I tried the update and the update didn't work but the alternative method you told me worked. So I think now you know your problem it will be easy to fix it now,

**Comment by AInoob** [comment]
Nice, so for people who install version between 0.1.2.x ~ 0.1.2.7, they will face this issue. I will make another update to fix this issue for those people. Thank you so much for the support!

**Comment by Droyk** [comment]
I can't believe anyone didn't reported this issue before

**Comment by AInoob** [comment]
Yeah, but here you are! I was wondering why high proportion of people removed NooBoss after they installed it, now I see the problem. If you didn't tell me, I will never notice it, because it works fine if you installed old version of NooBoss before.

**Comment by Droyk** [comment]
>If you didn't tell me, I will never notice it, because it works fine if you installed old version of NooBoss before.

Do you I just go to your extension support page https://chrome.google.com/webstore/detail/nooboss-extensions-manage/aajodjghehmlpahhboidcpfjcncmcklf/support

and found out one user did report this issue and you just didn't know what they are actually saying for example 
![image](https://cloud.githubusercontent.com/assets/15848350/23088321/7f4e2d8a-f5a1-11e6-8092-a79e1459c37b.png)

**Comment by Droyk** [comment]
Another thing I want to say is why don't you editout the link of the website and use the github one that way the normal user will know where to post the issues it too much a hassle to go out in your website and then click the github icon and then the icon will redirect you to the github page it too much of a time consuming simply make github your website how?

Github pages :  https://pages.github.com/
Examples: https://jasonlong.github.io/cayman-theme/
http://orderedlist.com/modernist/
http://madebygraham.com/midnight/
https://jasoncostello.github.io/slate/
