### ISSUE TITLE
你好，提个建议！

### ISSUE THREAD

**Issue by oenstep** [AInoob/NooBoss#31]
看到一个扩展
github地址(不知道是不是原作者)：https://github.com/solobat/Steward

chrome地址：https://chrome.google.com/webstore/detail/steward-%E6%89%A9%E5%B1%95%E5%BA%94%E7%94%A8%E6%A0%87%E7%AD%BE%E5%8E%86%E5%8F%B2%E8%AE%B0%E5%BD%95alfred/dnkhdiodfglfckibnfcjbgddcgjgkacd

原作者好像没有维护了，一些功能无法使用了。

此个扩展可以通过on+扩展名字 达到搜索指定扩展开启或者关闭（对于一些特别的扩展需要手动开关的有比较好的效果对于扩展特别多的朋友），里面还有其他一些功能。当前我是结合着二管家使用中。
主要是通过键盘操作吧，虽然有些朋友还是喜欢鼠标操作，希望作者看了之后能有一些想法吧！

**Comment by AInoob** [comment]
恩，好主意，这个已经有一个网友提了类似的想法了，我本来想这周末弄，但是上班太忙了，所以估计要拖一会，一定会开发这个功能的～
