### ISSUE TITLE
为啥用了这个以后，lastpass扩展时不时就会损坏啊

### ISSUE THREAD

**Issue by whwq2012** [AInoob/NooBoss#32]
别的扩展没有这个问题，就只有lastpass才有。
Windows10 1703
Chrome 60.0.3112.113

**Comment by AInoob** [comment]
Hello，不是很清楚，你没有把lastpass放到自动管理之中吧？如果没有，你可以考虑删除二管家试试，我感觉可能不是二管家的问题。

**Comment by K3info** [comment]
出现了同样的问题
Windows 10 1703
Chrome 61.0.3163.100（正式版本） （64 位）

没有把Lastpass放到自动管理中
但是开启二管家之后有一定几率会自动关闭移除Lastpass
尝试过移除重装二管家和Lastpass
情况没有改善。。。

同时被移除的还有
Avast Online Security | 12.0.296
Avast SafePrice | 12.0.296

不是很能理解这几位之间是否有冲突。。。

**Comment by AInoob** [comment]
二管家是没有权限移除任何程序的，你必须要手动点删除才可以。所以我不是很清楚到底发生了什么。你可以先卸载二管家试试，抱歉啦～
