### ISSUE TITLE
推荐功能的网址判断错误

### ISSUE THREAD

**Issue by zhtw2013** [AInoob/NooBoss#33]
https://imgur.com/jWkunFH.png

网址是www.google.com.tw 但是二管家判断成了.com.tw
没有正确判断Google的网址。

下面是二管家Chrome商店介绍的翻译
(话说我觉得繁体介绍页不用放更新日志，放功能介绍就好，日志外连可能比较好)
-------------------
一個全能的擴充功能管理和使用者指令碼管理工具
一個管理擴充功能用的工具，可使用擴充功能更新通知並記錄擴充功能使用歷程，自動開啟/關閉擴充功能，根據目前網站取得二管家社群推薦
擴充功能管理的最終利器，記錄擴充功能歷程，自動開啟/關閉擴充功能，根據目前網站取得二管家社群推薦
使用二管家全面掌控你的擴充功能吧！
通過二管家，你可以看到每個應用/擴充功能的詳細資訊，不管是它們需要的權限還是它們什麽時候更新的。
你也可以檢視二管家社群幫他們打了什麽標籤，這樣你就可以知道它們好不好用。你還可以設定自動規則，這樣擴充功能就只會在你開啟特定網頁的時候才開啟，其他時候都會關閉。

二管家提供的功能有：
*管理你的應用
---開啟/關閉/刪除一個或多個應用
*社群分享
---根據目前網頁看到二管家社群推薦的適用於目前網頁的擴充功能
---每個人都可以幫任何一個網站推薦好的擴充功能
---每個人都可以幫任何一個擴充功能打標籤
*自動套用狀態管理
---根據設定的規則自動啟用或停用應用
---(減少記憶體占用)
---(只有在需要的時候才開啟應用)
*應用歷程記錄
---記錄應用的安裝，移除，開啟，和關閉
---可以知道版本變化
*顯示應用詳細資訊
---下載crx檔案
---開啟manifest檔案
---檢視權限
---和各種各樣的詳細資訊

最近更新：
2017-09-17
   修復重要的自動管理bug
   修復UI bug
   修復背景錯誤資訊bug
2017-09-10
   修復取得語言bug
2017-09-06
   增加繁體中文，感謝zhtw2013
   修復UI bug
2017-09-04
   修復一個小的UI Bug
2017-09-02
   哪裏都有顯示模式了
   微小的介面調整，更漂釀了
2017-09-01
   修復自動管理邏輯bug，大大加快了頁面載入速度
   修復自動管理邏輯bug，不再蛋疼的重新整理了
   修復色彩選擇bug
2017-08-31
   修復自動管理通知bug
   在歷程頁面增加了清理歷程按鈕
   大大減小了大小！
   最佳化導覽顯示
   增加大磚塊顯示！
   讓導覽懸浮在上面
2017-08-27
   大更新，重寫了全部，太多了，不說了
   可以變更主題色彩
   可以刪除單條歷程記錄
   可以記錄二管家的更新
   大大減少尺寸
   可以關閉加入社群功能
   更快的擴充功能推薦
   可以復原，退回在擴充功能管理頁面的操作
   可以重置縮放，保證好看的布局
   動態載入更多歷程記錄和擴充功能推薦
   還有好多我不記得的更新。。。
2017-07-02
　　修復自動掛你bug！
2017-07-02
　　修復自動管理bug！
2017-07-01
　　增加分組！
　　修復匯出設定bug
　　支持萬用字元！
　　自動管理支持分組了~
2017-06-18
　　修復應用頁面bug，es6
2017-05-11
　　修復錯別字
　　你可以選擇記錄什麽歷程了！
2017-03-18
　　修復AutoState的幾個bugs
　　增加Chrome管理選項的選項
2017-03-05
　　更新基礎介面
2017-02-21
　　修復Mac閃退問題
　　美化彈框
2017-02-18
　　在自動管理增加目前網頁按鈕
　　刪除加入社群
　　修復UI的bug
2017-02-17
　　新的自動管理嚴重bug
2017-02-16
　　自動管理嚴重bug
　　修復UI的bug，調整關於頁面，刪除加入社群選項
2017-02-14
　　修復清楚歷程的bug和UI的bug
2017-02-11
　　修復自動管理的一個致命bug，現在二管家可以起飛了~
2017-02-10
　　增加通知時長設定
2017-02-08
　　新UI！修復幾個bugs。增加推薦擴充功能選項
2017-02-07
　　在自動管理中增加"只有符合才停用"選項

**Comment by AInoob** [comment]
匹配规则的确不是很靠谱，哈哈，感谢回复。更新历史这个暂时就不会动了，有些懒得改～

匹配的这个没有什么太好的办法，暂时不会修改。估计等回头准备大更新的时候才会考虑了～

**Comment by AInoob** [comment]
想了想，小改动而已，于是修复x.com.*, x.net.*, x.gov.* 的问题了，再次感谢！ 版本0.1.6.5
