### ISSUE TITLE
分组失效问题

### ISSUE THREAD

**Issue by sufanx** [AInoob/NooBoss#34]
当我创建好一个分组，然后删除分组中的某一个插件（拓展？扩展程序？），这个分组将不能正常工作，只能删除然后新建组，重新部署。

**Comment by sufanx** [comment]
额，退一步的话，我可以先把我需要移除的插件从分组中移出，然后再移除，但是如果我有多个分组，这是一个问题。

**Comment by AInoob** [comment]
感谢提交bug，这个的确是一个bug，会马上修复的（3小时之内，版本0.1.6.6）。
再次感谢！

**Comment by AInoob** [comment]
已经修复，大概2小时后会更新～ 感谢提交bug！
