### ISSUE TITLE
Improve responsiveness with lots of extensions

### ISSUE THREAD

**Issue by malore** [AInoob/NooBoss#35]
I have more than 100 extensions (for the most part disabled) and NooBoss takes something like 10-15 seconds to load. It'd be nice if NooBoss were more responsive because I'd like to use it for quickly enabling/disabling other extensions. Maybe add an option to load extensions before clicking NooBoss button and keep them in memory. I don't know if it's possible.

**Comment by AInoob** [comment]
Wow, 10-15 seconds is definitely not a good experience. I will definitely find a way to fix this issue. Right now I cannot tell when this will be fixed, I am guessing around 1 hour to 1 week.

**Comment by AInoob** [comment]
Can you please send me a gif about loading? I am trying to figure out which part is slowing down the loading, thank!

**Comment by AInoob** [comment]
Man, after installing 110+ extensions, I do see some lag in NooBoss, but it took less than 2s for NooBoss to load. I am not sure why your loading is that slow, so a gif or video would greatly help.

**Comment by AInoob** [comment]
Hello there, now I have improve the loading speed of NooBoss, it loads images much faster. Version 0.1.6.8.

**Comment by malore** [comment]
Yes, absolutely true. Now it takes only 2-3 seconds to load, a way more reasonable time. Thank you for your time and efforts!

**Comment by AInoob** [comment]
Thank you for the feedback!
