### ISSUE TITLE
Problem with groups

### ISSUE THREAD

**Issue by malore** [AInoob/NooBoss#36]
I can't manage to view some groups of extensions I've previously created: when I click on them appears only a blank rectangle and nothing more. Furthermore, it's impossible to write group names quikly because all the letters between the first and the last are skipped.

**Comment by AInoob** [comment]
Hello there, can you please send me a screenshot and your configuration? Things looks okay in my NooBoss, so I need more information to figure out what's going on

**Comment by AInoob** [comment]
Bug fixed, the update should come in 2 hours. Thank you again for your feedback!

**Comment by malore** [comment]
Thank you!
