### ISSUE TITLE
Not showing extension icons in Groups and Autostate

### ISSUE THREAD

**Issue by malore** [AInoob/NooBoss#38]
I don't know if it's connected to the loading issue, but recently I don't see images of extensions added to an Autostate rule or a Group (they regularly appear in the list of all extensions).

![Autostate](https://user-images.githubusercontent.com/16622109/31676786-f40112c0-b368-11e7-8389-ca43e78fb527.PNG)
![Groups](https://user-images.githubusercontent.com/16622109/31676828-1fd9c9be-b369-11e7-8281-ebd14c2837d5.PNG)

**Comment by AInoob** [comment]
Oh, this is a new bug, because I made the loading faster, I forgot to update this part. Will update in 2 hours. Thank you again for your feedback!

**Comment by AInoob** [comment]
Bug fixed, version 0.1.6.9. Thank you again!
