### ISSUE TITLE
[Feature Request] Add a url box in autostate page that have all currentlly open sites url

### ISSUE THREAD

**Issue by Droyk** [AInoob/NooBoss#4]
So I want you to ease my work a little and I think others users will like this too 
it takes time to write up the whole URL and 90% of the time user on the website which they want to add an auto state rule on so I thought it would be a really good idea to implement this  

![untitled-1](https://cloud.githubusercontent.com/assets/15848350/23086551/9e214c0a-f593-11e6-8f2c-f5ececc53de9.png)

this image isn't really that good but you know what I am talking about
so what do you think?

**Comment by AInoob** [comment]
This is actually a very good idea! I think I will implement this tonight.

**Comment by Droyk** [comment]
really glad to hear that.

**Comment by AInoob** [comment]
Current website button is added to AutoState, so I will close this issue now.

**Comment by Droyk** [comment]
Can't you add all the website that are currently open in the browser so then the user will be able to easily choose websites.

**Comment by AInoob** [comment]
I don't think that is a good idea, because I open more than 20 tabs all the time, and only few of them should be matched.
