### ISSUE TITLE
[Feature request] View at a glance which groups every extension belong to

### ISSUE THREAD

**Issue by malore** [AInoob/NooBoss#40]
It would be useful to see, maybe through tags, which groups extensions belong to because It would allow to spot if I forgotten to add some extensions to a specific group and if some extensions do not belong to any group.

**Comment by AInoob** [comment]
Agree! Will put this in the to-do list~

**Comment by AInoob** [comment]
Hi, now if you open extension detail, you will see the row "Group", which means the groups that contain this extension.

Thank you for the feature request.
