### ISSUE TITLE
希望可以增加排序功能

### ISSUE THREAD

**Issue by zhzjwd** [AInoob/NooBoss#42]
很喜欢这个扩展，尤其是自动管理这个功能，太实用了，但是个人在使用过程中还是有点建议想要提一下

就是增加排序功能，
比如启用的扩展自动置顶；
或者某个组里的扩展在本组自动置顶；
或者加入自定义排序，可以自己对扩展排序；

这样更容易找到需要的扩展，因为有很多扩展是无法通过自动管理功能打开的，它们并不是在特定的某几个网站才需要，而是指不定在哪个网站就需要了，但这个扩展又不是要一直开启，这种扩展什么时候启用什么时候禁用全靠自己的心情；

就像二箱这个扩展，就不能通过自动管理使其只在需要的时候开启，虽然可以通过正则设置在含有图片后缀的标签自动启用，然后手动将图片在新标签页打开，但是很多时候图片地址中是不含有后缀名的，只能手动开启扩展，手动的话就需要最快速的找到这个扩展，这时候分组内自动置顶或者自定义排序就能发挥很大作用；
现在二箱的排序规则是什么我一直没搞明白，我自己的几十个扩展排序一直都是乱糟糟的。

另外建议将启用和禁用的高亮做得明显一些，就类似编辑分组时那样的，现在启用和禁用的扩展之间的差别有点小，就像图里的：
![test](https://i.loli.net/2017/10/25/59f09538834e0.png)
很多扩展图标颜色并不是那么鲜艳，甚至本身就是黑白色图标，导致第一眼看上去不容易分辨出哪个是启用的哪个未启用，如果扩展数量比较多，就更不容易区分了。

总结一下，就是希望在需要的时候能更快速的找到所需扩展。

多谢了

**Comment by AInoob** [comment]
很好的建议！其实这些都是我想改进的。
1. 排序一直在二管家的todo里面，只是最近没有心情和精力弄
2. 启用禁用的区分这个我也发现了，的确是有点分不清，会想办法的！
很开心收到你的建议，我明天找个时间弄一下~

**Comment by AInoob** [comment]
最近有点懒，估计要过几周才弄了~

**Comment by zhzjwd** [comment]
不着急，当然是啥时候有时间啥时候弄，这也不是刚需

**Comment by AInoob** [comment]
嘿，排序已经弄完了，版本0.1.7.1.
可能要过几个小时谷歌才会更新。
如果有问题欢迎告诉我哦～

**Comment by AInoob** [comment]
然后下一个版本（也会很快发布）我会把那些关闭的拓展的显示弄得更清楚一点
