### ISSUE TITLE
希望增加浏览器同步功能

### ISSUE THREAD

**Issue by czmecho** [AInoob/NooBoss#45]
虽然已经有备份和导入功能，但还是浏览器同步最方便。现在很多chrome扩展都支持浏览器同步数据了，如果增加这功能不难的话，希望开发者能增加。谢谢。

**Comment by AInoob** [comment]
默认应该会同步一些（还是全部不记得了。。。）设置，感谢建议，回头会添加的~

**Comment by AInoob** [comment]
嗨，默认会同步不少数据。所以暂时就关闭这个issue了。
