### ISSUE TITLE
Nooboss doesn't disable the extension when i leave the site

### ISSUE THREAD

**Issue by Avrozavr** [AInoob/NooBoss#48]
Hello, first of all, thanks for the great extension.

I set up some extensions to use only on certain sites, and the extension really turns them off on startup, but if I leave the site, they stay on. I tried to use both, enable only and enable when, didn't notice any difference.
I am using latest stable chrome version.

**Comment by janstieler** [comment]
Same Problem here!

**Comment by qwer1304** [comment]
I have a similar problem but in the other direction: I set up NooBoss to **disable** an extension on a certain site and indeed it disabled it when I navigated to the site, but then it left it **disabled** for good (i.e., it did not re-enable it).

On another note, it seems that this design is **flawed**: consider a case of pdf.js extension (JS-based viewer which replaces Chrome's native pdf plugin). I need to disable it on a certain site. If I have some tabs open in the extension, then go to that site NooBoss disables pdf.js, I'd loose all the other tabs. This is unacceptable.

**Comment by AInoob** [comment]
Hello, sorry for the late reply. I will check what's going on now.

**Comment by AInoob** [comment]
@Avrozavr Can you please tell me if you are setting as enable only or just enable? I tried with enable only and it works fine.

**Comment by AInoob** [comment]
@qwer1304 Can you please check if you are setting as disable only or disable? Disable only might be what you are looking for.

As for the note, you are right, it is not acceptable. But that is managed by Chrome, so in no way can NooBoss make it enable for tab A but not tab B.

**Comment by qwer1304** [comment]
@AInoob The setting originally was Disable when. I changed that to Disable only, but then NooBoss does NOT disable the extension when I navigate to site.

PS You'd better make a BIG note that NooBoss disables an extension on ALL open tabs irrespective of the site they were opened on.

**Comment by AInoob** [comment]
@qwer1304 Disable only should make it work, maybe the match was wrong. 

And yes, I should mention that it applies changes on all tabs.

**Comment by devcline** [comment]
hello is theire anyh tutorial on **HOW TO** enable on specific website and HOW TO disable on all other sites when leave it . thanks

**Comment by mikhoul** [comment]
[**@devcline**](https://github.com/devcline) commented on [8 août 2018 à 21:56 UTC−4](https://github.com/AInoob/NooBoss/issues/48#issuecomment-411612174 "2018-08-09T01:56:38Z - Replied by Github Reply Comments"):
> hello is theire anyh tutorial on **HOW TO** enable on specific website and HOW TO disable on all other sites when leave it . thanks

Use "**ENABLE ONLY**" and it will be enabled only othe website(s) you choose. :octocat:

**Comment by laerhu** [comment]
请问如果不能实现在特定网站关闭指定扩展的话，disable only 和 disable when 的设计用途是什么呢？需求场景是：工作时的网页大部分是公司网页，自动关闭无关扩展能节省很多内存。
