### ISSUE TITLE
[Feature Request] Add a indication in autostate mode if a extension is enable or disable

### ISSUE THREAD

**Issue by Droyk** [AInoob/NooBoss#5]
There is no indication in autostate mode that says the extension is enable or disable so plz add it and another thing I saw is whenever I closes its window it forget the url and the extension and scroll state I choose plz add a saving feature to never let the extension forget those things
and icons in autostate mode are too big make them small if a user have many extensions they have to scroll really down to see them if you can't then add a choice so the user will decide what's good for them.

**Comment by AInoob** [comment]
For remembering previous state, it will not be very simple, so I will not do this yet. For icon, I will add a selection within in a month. Thank you for the support!

**Comment by AInoob** [comment]
Now you can change the view mode, so if you choose list view, the icons are relatively small.
