### ISSUE TITLE
Question about an advanced option

### ISSUE THREAD

**Issue by mikhoul** [AInoob/NooBoss#53]
What is the purpose of the Zoom in NooBoss ? 

![image](https://user-images.githubusercontent.com/5678673/41010846-e62a7c04-6907-11e8-9318-3b9995b31b39.png)

Regards :octocat:

**Comment by AInoob** [comment]
It's to make NooBoss looks good, if you are on a high dpi machine, it will show a difference, but if not, then it does not matter.
