### ISSUE TITLE
Bug with History and Notifications

### ISSUE THREAD

**Issue by mikhoul** [AInoob/NooBoss#54]
I'm not sure if it is a real bug or a limitation of the Chrome API but if I reload/update the chrome://extensions/ page there is many new events that are logged in the history page and there is also Notifications that appear even if nothing changed  in the extensions.

Also when I click on the "Empty History" button again there is Update Notification that show up even if nothing was updated.  **NOTE**: I don't know if it's important but those extensions are loacal and loaded from my system in dev mode.

Look at the Screencast here it will be more easy to understand what I mean: http://screencast-o-matic.com/watch/cF112ybSOk

Regards :octocat:

**Comment by mikhoul** [comment]
More Information about the notifications "bug" here: http://screencast-o-matic.com/watch/cF11onbSuK

**Comment by mikhoul** [comment]
@AInoob   It's me again,   

I use an extension that updated and I use  this extension: https://chrome.google.com/webstore/detail/extensions-update-notifie/nlldbplhbaopldicmcoogopmkonpebjm?utm_source=chrome-app-launcher-info-dialog that like your addon warn me that if an update occur via the Notifications.

So an update occurred on ONE of my addon like you can see here: 

![image](https://user-images.githubusercontent.com/5678673/41059553-e17fea66-699a-11e8-82fe-099d1206c94a.png)

But NooBoss instead of warning me like it should displayed "false" notifications about the same 3 extensions you can see the previous screenshot that those extension were updated which is false since those extensions unpacked extensions installed by me locally on my system.

I'm pretty sure it have to do with the same issues as my previous messages.

I just hope it will help you to pinpoint better the cause of this bug.


Regards :octocat:

**Comment by mikhoul** [comment]
@AInoob  

There is a more important bug now:  I'm using a download manger that use Notifications to warn me the the download is completed so everytime I download something NooBoos notification show up lithe those:

![image](https://user-images.githubusercontent.com/5678673/41115870-cf7f563c-6a56-11e8-97ba-2874980c0a39.png)

Those 3 extensions again are unpacked extensions that  I have installed myself so the update Notifications of NooBoss are wrong.

Regards :octocat:

**Comment by AInoob** [comment]
Thank you for the feedback, I will try to fix them, but the time is unknown for now.

**Comment by Tikotik** [comment]
This is too annoying. Could you please checkout? @AInoob

**Comment by AInoob** [comment]
Thank you for reminding me, @Tikotik . The reason that I pretty much stopped updating NooBoss is simply that I do not gain much achievement from writing it. I do understand that it's annoying, but maybe the time I spent on it is not proportional to the happiness I gain from it. Anyway, I will re-think about what should I do with NooBoss, and maybe start fixing bug soon.

**Comment by AInoob** [comment]
Hi, please let me know if the issue still exists. I am closing it for now.
