### ISSUE TITLE
[Feature request] Forbid users to disable extensions if they want it

### ISSUE THREAD

**Issue by kilometrix** [AInoob/NooBoss#57]
How about adding a function that will not allow to disable an extension? This will be helpful for those who use extentions that do not let users to visit time-wasting sites at work (StayFocused etc.). Because if there is a possibility to bypass a restriction, it will be bypassed :)

**Comment by AInoob** [comment]
Thank you for your suggestion. However this is not possible since Chrome does not provide extension with this much permission. To force enable one extension, you might want to check something related to group policy at the system level.
