### ISSUE TITLE
扩展更新却提示安装

### ISSUE THREAD

**Issue by ghost** [AInoob/NooBoss#59]

**Comment by AInoob** [comment]
感谢反馈,这个的确是一个问题。不过暂时不会修复了，因为没有太多激情写二管家。。。

**Comment by iwanfu** [comment]
@AInoob 难道不是写给自己用的吗？ ╮(๑•́ ₃•̀๑)╭

**Comment by AInoob** [comment]
是的呀，但是平时也就看看哪些拓展更新了，这个错误的话，懒的改。。。或许要一段时间之后才会更新了

**Comment by AInoob** [comment]
嗨，上周更新了二箱，这周末争取把这个问题修复了

**Comment by AInoob** [comment]
嗨，我尝试修复了一下，版本0.1.7.2 . 

如果还有问题，欢迎重开这个issue
