### ISSUE TITLE
新建组中文重命名时出现字符谜之重复

### ISSUE THREAD

**Issue by Xiaotouming** [AInoob/NooBoss#64]
微软自带输入法

**Comment by komazhou** [comment]
存在同样的问题，不过作者现在好像没有太多时间维护了，可惜

**Comment by AInoob** [comment]
嗨，下周会尝试更新NooBoss，到时争取修复这个问题。
的确很久没有维护了。。。

**Comment by AInoob** [comment]
我测试环境
Deepin LInux + 搜狗拼音

Mac os + 自带拼音　有问题，没法输入中文。

所以你们遇到的跟Mac os遇到的差不多？

**Comment by AInoob** [comment]
嗨，bug应该修复了，新的版本正在发布，0.1.7.3.

如果还有问题，欢迎告诉我～
