### ISSUE TITLE
Sorting of extensions in alphabetical order

### ISSUE THREAD

**Issue by smaragdus** [AInoob/NooBoss#66]
I would appreciate an option to sort extensions in alphabetical order- new check box in Options:

- Sort extensions in alphabetical order

For me such an option would facilitate browsing extensions.

**Comment by everruler** [comment]
I would really appreciate this too!

**Comment by AInoob** [comment]
Hi, thank you for the feature request.

I will try to make an update on NooBoss next week.

**Comment by smaragdus** [comment]
@AInoob 
I am glad the extension is not abandoned.

**Comment by AInoob** [comment]
Last week I was working on NooBox, and release a new version. I will make an update today or tomorrow to support this feature.

**Comment by AInoob** [comment]
Hi, sorting is supported now! Version 0.1.7.1.

Please let us know if you see any issue.

Thank you for suggesting the feature.

**Comment by smaragdus** [comment]
@AInoob 

> Hi, sorting is supported now! Version 0.1.7.1.

Excellent news!

> Please let us know if you see any issue.

[NooBoss](https://ainoob.com/en/project/nooboss) hasn't been updated yet at [Chrome Web Store](https://chrome.google.com/webstore/detail/nooboss/aajodjghehmlpahhboidcpfjcncmcklf) - it is still at version 0.1.7.0. I suppose that Chrome Web Store needs some time to update the extension to the latest version (0.1.7.1). When I get the updated version of [NooBoss](https://github.com/AInoob/NooBoss) I will test it and if it happens that I encounter problems I will report them.

> Thank you for suggesting the feature.

I am glad that NooBoss is not abandoned- I find it very useful!

Best regards

**Comment by smaragdus** [comment]
@AInoob 

NooBoss was finally updated to version 0.1.7.1 at Chrome Web Store and I tested it. For me it is easier to browse through extensions when they are sorted alphabetically, thanks!

**Comment by AInoob** [comment]
No problem! :)
