### ISSUE TITLE
Will it still update?

### ISSUE THREAD

**Issue by wang-xudong** [AInoob/NooBoss#67]
I found this extension's last update is 2 years ago, and there are some bugs has not fixed. So I want to know if the extension will update in some day. But even this extension will not update anymore, I still appreciate so much to the author.

**Comment by AInoob** [comment]
Hi, Xudong,

I would call the current status as dormant.
I am not sure whether I will resume the development or not. 
The main reason is that I personally do not see a big use case of the extension. (I have not open NooBoss in past few months)

Thanks,
AInoob
