### ISSUE TITLE
Tick able settings

### ISSUE THREAD

**Issue by MicroBeast** [AInoob/NooBoss#7]
I mean for
- Tick able Allow for incognito 
- Tick able Collect errors
- Tick able Allow access to file URLs.
If not possible, then a link like "Manage Extensions" do is sufficient.

Thank you.

**Comment by AInoob** [comment]
Hello MicroBeast, thanks for the feedback!

I think all these cannot be access by NooBoss, but I will definitely add a link to manage extensions with id.

The update will be released within a month.

**Comment by MicroBeast** [comment]
That's nice.

Thank you very much.

**Comment by AInoob** [comment]
Hello MicroBeast, finished! In version 1.3.4 or after, there will be an icon that lead you directly to Chrome Extension manage page. Thank you again for the feedback! Personally I found this very useful!
