### ISSUE TITLE
Top bar becomes quite big. 顶栏偶尔变得很大

### ISSUE THREAD

**Issue by Nelson0491** [AInoob/NooBoss#76]
Sometimes the top bar becomes so big when I click the icon on the menu that I can't see any extensions. I have to wait or restart the NooBoss.
有时我点开二管家时顶栏变得巨大，我只能看到几个大字。我需要等待或重启二管家才能恢复正常。
![nooboss](https://user-images.githubusercontent.com/59787059/72215136-ed662300-3549-11ea-9ca5-d2416d432396.png)

**Comment by AInoob** [comment]
哇，感谢反馈～

看来不是个例。。。会尽快修复的～

**Comment by iYato** [comment]
same for me

**Comment by AInoob** [comment]
已经提交了修复了，可是谷歌一直没通过。。。很抱歉，希望过几天可以通过审核。

**Comment by Nelson0491** [comment]
没关系，这是一个功能独一无二的插件，就用正则表达式匹配网站来说，无可替代，希望你们越做越好！

**Comment by goodbetterbest666** [comment]
同样问题，前来围观

**Comment by AInoob** [comment]
@goodbetterbest666 谷歌一直不给通过。。。我今天再提交一次试试。。。

**Comment by Nelson0491** [comment]
听说最近谷歌审核机制严格了很多。。。

**Comment by 023Sparrow** [comment]
同样问题，被折磨的装了第二个扩展管理

**Comment by AInoob** [comment]
谷歌又给我拒绝了。。。非常难受。。。。

**Comment by Kmyu1k** [comment]
> 谷歌又给我拒绝了。。。非常难受。。。。

能在微软的插件商店 Microsoft Edge Addons 上架嘛？

**Comment by AInoob** [comment]
Hi，现在问题应该修复了~

**Comment by AInoob** [comment]
> > 谷歌又给我拒绝了。。。非常难受。。。。
> 
> 能在微软的插件商店 Microsoft Edge Addons 上架嘛？

这周末我看看，如果兼容就上架。目测只能在那个Chrome内核的Edge上架。
