### ISSUE TITLE
UI is totally destroyed on Chromium 78. Random white text characters on black background.

### ISSUE THREAD

**Issue by Botspot** [AInoob/NooBoss#77]
When I click Nooboss, it looks like this:
![screenshot](https://i.ibb.co/QkfWmKy/2020-01-16-202510-1280x1024-scrot.png)
Upgraded to Chromium 78 today and the problem immediately occurred.
Reinstalling Nooboss fixes its UI temporarily until the next time Chromium is restarted, when the problem returns.

**Comment by AInoob** [comment]
Wow, this is crazy! I do have some idea about what's going on... But I don't think it's easy to reproduce it.
Thank you for the feedback! I will keep this issue opened.

**Comment by AInoob** [comment]
Looks like many people faced the same issue. I will make a fix soon.

**Comment by Botspot** [comment]
Still happening. Any updates?

**Comment by AInoob** [comment]
Hi, Google rejected my update... I have submitted 3 times. Will reach out to Google and see what's going on.

**Comment by Botspot** [comment]
The UI has subtle differences. Looks like the update came through.
I have yet to see if the problem persists.

**Comment by AInoob** [comment]
Good to hear it's working now~ 
Google finally approved my update.
