### ISSUE TITLE
【请把二管家和二搜....都增加一个点击按钮显示独立窗口选项】

### ISSUE THREAD

**Issue by Noah1995** [AInoob/NooBoss#78]
![【2020 02 14】【15 ：51 ：59】](https://user-images.githubusercontent.com/25548230/74511919-0d6e7500-4f42-11ea-8525-73cf2fa9a9f2.gif)

1丶类似[smms图床](https://chrome.google.com/webstore/detail/smms%E5%9B%BE%E5%BA%8A/jfnojkljiahflcnlodkicgfbofclmdoi)和[沙拉翻译](https://saladict.crimx.com/)这样

因为比如打开商店的时候跳转页面后丢失拓展页面...
需要重新打开而且它也不记忆之前位置...

2丶最好也能增加记忆之前关闭位置选项...

**Comment by AInoob** [comment]
嘿，感谢提供建议。暂时不考虑了。。。比较懒。
不过
chrome-extension://aajodjghehmlpahhboidcpfjcncmcklf/popup.html?page=options
和
chrome-extension://hpbllcjhfcccgjfooobibpbjclihdbap/popup.html
可以在一个标签页打开~
