### ISSUE TITLE
Difference between "enable when matched" and "only enable when matched" in AutoState?

### ISSUE THREAD

**Issue by karanrajpal14** [AInoob/NooBoss#8]
There seems to be no documentation about that. Both seem to have the same effect and sound almost the same. Also, there seems to be no indication that it is working. Irrespective of what rule I add, the extension buttons remains visible in my extensions bar. Can you please add some documentation and help me out with this?

**Comment by AInoob** [comment]
Hello there, sorry for the slow response(I just noticed this issue).

enable when matched means if you close the matching website, the extension will not be disabled.
only enable when matched mean if you close the matching website, the extension will be disabled.
