### ISSUE TITLE
what's the situation?

### ISSUE THREAD

**Issue by Vstory** [AInoob/NooBoss#80]
After installation, click on Extensions.
Shown below:
![Snipaste_2020-03-09_20-11-14](https://user-images.githubusercontent.com/20795557/76211972-603a0480-6242-11ea-8749-bb3b1d279f00.png)

**Comment by illucent** [comment]
The same issue. Awesome extension overall but sometimes, randomly, not always, the UI is not properly rendered.

**Comment by AInoob** [comment]
Hi, please try update NooBoss now, the issue should be fixed.
