### ISSUE TITLE
在打开浏览器之后点开插件界面会变得特别大

### ISSUE THREAD

**Issue by w1718w** [AInoob/NooBoss#82]
如图
![批注 2020-03-31 082636](https://user-images.githubusercontent.com/42036727/77974318-58452000-7329-11ea-9840-443f82b9715f.png)
在chrome和新版Edge上都有出现
版本：
Microsoft Edge 是最新版本。
版本 80.0.361.69 (官方内部版本) (64 位)

CHROME是
版本 80.0.3987.132（正式版本） （64 位）

Windows10专业版 1909

edge信息：
Microsoft Edge	80.0.361.69 (官方内部版本) (64 位)
修订	11b2f9c770113c9712ab7dffaca9ea3596d0deb3
操作系统	Windows 10 OS Version 1909 (Build 18363.720)
JavaScript	V8 8.0.426.27
Flash	32.0.0.303 C:\WINDOWS\system32\Macromed\Flash\pepflashplayer64_32_0_0_303.dll
用户代理	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36 Edg/80.0.361.69
命令行	"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --flag-switches-begin --flag-switches-end --enable-audio-service-sandbox
可执行文件路径	C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
配置文件路径	C:\Users\Administrator\AppData\Local\Microsoft\Edge\User Data\Default
差异	202c099d-ca7d8d80
f39a7e69-ca7d8d80
7b1b2ab3-ca7d8d80
4ea303a6-ca7d8d80
b76f455-ca7d8d80
3ee6367e-ca7d8d80
daff722c-d8d26f5e
2207c1a2-d8d26f5e
d8db6806-d8d26f5e
9539fc9e-d8d26f5e
8aef1b08-d8d26f5e
1a96c400-d8d26f5e
c0eba975-ca7d8d80
44b18228-d8d26f5e
f959761-d8d26f5e
4914d477-d8d26f5e

扩展列表：
![批注 2020-03-31 083108](https://user-images.githubusercontent.com/42036727/77974537-03ee7000-732a-11ea-8617-66f3c4884e78.png)
![批注 2020-03-31 083121](https://user-images.githubusercontent.com/42036727/77974538-06e96080-732a-11ea-8b63-5f912f2f3254.png)

**Comment by AInoob** [comment]
Hello，问题应该已经修复了~
