### ISSUE TITLE
希望作者能在Microsoft Edge Addons微软拓展商店上架此应用！

### ISSUE THREAD

**Issue by Kmyu1k** [AInoob/NooBoss#83]
新版edge也是chromium内核了，希望能在这里Microsoft Edge Addons微软拓展商店上架该插件，方便用户

**Comment by AInoob** [comment]
感谢提醒，这周末打包~

**Comment by AInoob** [comment]
当然我会先看看现在兼容不兼容，如果不兼容，应该暂时不会更新。。

**Comment by AInoob** [comment]
https://microsoftedge.microsoft.com/addons/detail/noobox/jacoeejpmihiopgohinegbiekdombfde

当当当当，上架了～

感谢建议～

**Comment by SylleoYr** [comment]
> 
> 
> https://microsoftedge.microsoft.com/addons/detail/noobox/jacoeejpmihiopgohinegbiekdombfde
> 
> 当当当当，上架了～
> 
> 感谢建议～

上架的是二箱，怎么没有二管家啊 😢
