### ISSUE TITLE
自動管理禁用擴展可否設定只在瀏覽該網站分頁時禁用

### ISSUE THREAD

**Issue by hwj69819** [AInoob/NooBoss#86]
如題，設定當比對特定網址A關閉擴展後，擴展會確實關閉，但是當暫時跳到別的B分頁瀏覽時，擴展仍是關閉的，除非將特定網址A的分頁全數關閉後才會重新開啟擴展，可否增加比對僅停留在瀏覽特定網址A時才關閉，以前有看過其他project有類似的實作，我想應該是有可行性的。

**Comment by AInoob** [comment]
Hello，目前来说，一旦禁用某个扩展那那个扩展就会完全关闭。NooBoss是做不到的。
扩展自己本身可以根据不同页面选择是否开启。
