### ISSUE TITLE
Autostate stopped working

### ISSUE THREAD

**Issue by cannedenthusiasm** [AInoob/NooBoss#9]
It worked at first, but after a while the Auto-state stopped working. 
I've tried uninstalling & reinstalling, but it didn't help anything. What can I do next?

I found that I had to completed remove all my configurations and start from scratch with my configuration to get it working again. I don't know what caused this, but I'll keep you posted, if I figure it out. Love this plugin though.

**Comment by AInoob** [comment]
Thank you for the feedback! Can you find a way to reproduce this issue? If yes, can you please tell me how? So I can follow the steps and figure out what's wrong.

**Comment by AInoob** [comment]
Closing this issue since no response for a while.
